通过100道题目带你快速玩转Numpy

In [12]:
# 1.导入numpy库¶
import numpy as np

In [13]:
# 2. 打印numpy的版本和配置说明
print(np.__version__,np.show_config)

1.16.2 <function show at 0x000001B754DF57B8>


In [14]:
# 3. 创建一个长度为10的空向量
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
#4.  如何找到一个数组的内存大小（size, itemsize）
z = np.zeros((10,10))
z.size*z.itemsize

800

In [17]:
#5. 从命令行得到numpy中add函数的说明文档
numpy.info(numpy.add)

NameError: name 'numpy' is not defined

In [18]:
#6.创建一个长度为10并且除了第五个值为1的空向量
Z = np.zeros(10)
Z[4] = 1
Z 

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [23]:
# 7.创建一个值域范围从10到49的向量
Z = np.arange(10,50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [25]:
# 8.反转一个向量（第一个元素变为最后一个）
Z = np.arange(50)
Z = Z[::-1]
Z 

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [28]:
# 9.创建一个3*3并且值从0到8的矩阵
Z= np.arange(0,9).reshape(3,3)
Z 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
# 10.找到数组[1,2,0,0,4,0]中非0元素位置索引
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

In [33]:
# 11.创建一个3*3的单位矩阵
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
# 12.创建一个3*3*3的随机数组
np.random.rand(3,3,3)

array([[[0.38570956, 0.8548085 , 0.39294576],
        [0.63859333, 0.79952265, 0.49624542],
        [0.47207224, 0.35438395, 0.50221111]],

       [[0.14740037, 0.30305305, 0.39631028],
        [0.28089223, 0.00500958, 0.42117635],
        [0.00718553, 0.05882071, 0.2395312 ]],

       [[0.93740261, 0.06119003, 0.29444386],
        [0.03393079, 0.79760018, 0.19724008],
        [0.43242972, 0.01705738, 0.52048627]]])

In [43]:
# 13.创建一个10*10的随机数组并找到它的最大值和最小值
z = np.random.random((10,10))
print(z,z.max(),z.min())

[[0.79285285 0.63993584 0.34718424 0.03983129 0.53874739 0.63004277
  0.11518807 0.18823584 0.2292957  0.12628212]
 [0.72256724 0.88240832 0.1421028  0.83705561 0.07262972 0.51410365
  0.60176725 0.78495922 0.786486   0.63286964]
 [0.47993099 0.50362725 0.71676587 0.03121469 0.69885439 0.98987401
  0.09456061 0.66990272 0.44227897 0.97223177]
 [0.42744519 0.75397568 0.8610391  0.94440856 0.52371065 0.59681353
  0.88045075 0.38814031 0.83812674 0.60306949]
 [0.33422512 0.12581188 0.75337873 0.69707685 0.47980802 0.16733611
  0.13634014 0.46566163 0.7934456  0.26586908]
 [0.60729346 0.57702792 0.01723233 0.09701452 0.88609563 0.34565641
  0.07544226 0.28857325 0.66672805 0.69318866]
 [0.5761777  0.42402781 0.39559152 0.0761273  0.62443227 0.45666658
  0.35598629 0.88698867 0.81373196 0.44612688]
 [0.23576511 0.72553391 0.90049162 0.8677019  0.40255698 0.23310997
  0.80315628 0.34591077 0.2400237  0.161664  ]
 [0.3915425  0.43915462 0.24331456 0.97305821 0.91662426 0.35390197
  0.89286017

In [44]:
# 14.创建一个长度为30的随机向量并找到它的平均值
np.random.randn(30).mean()

-0.15712639403435477

In [45]:
np.random.random(20)

array([0.09242661, 0.01114453, 0.73271228, 0.36490847, 0.0595079 ,
       0.97001314, 0.92033314, 0.31819772, 0.9062723 , 0.4034435 ,
       0.38090905, 0.07566907, 0.38357751, 0.20217087, 0.50300259,
       0.66369709, 0.37634599, 0.36035126, 0.12411834, 0.87067018])

In [49]:
# 15.创建一个二维数组，其中边界值为1，其余值为0
z = np.ones((10,10))
z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [51]:
# 16.对于一个数组，如何用0来填充边界
z = np.ones((1,1))
z = np.pad(z,pad_width=1,mode='constant',constant_values = 0)
z 

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.]])

In [52]:
# 17.下面表达式运行的结果分别是什么
0 * np.nan

nan

In [53]:
np.nan == np.nan

False

In [54]:
np.inf > np.nan 

False

In [55]:
np.nan - np.nan

nan

In [56]:
0.3 == 3*0.1

False

In [61]:
# 18. 创建一个5*5的矩阵，并设置值1，2，3，4落在期对角线位置
z = np.diag(1+np.arange(4),k=-1)
z 

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [65]:
# 19.创建一个8*8的矩阵，并设置成棋盘样式
z = np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
z 

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [66]:
# 20.考虑一个（6，7，8）形状的数组，其第200个元素的索引（x，y，z）是什么？
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [67]:
# 21.用tile函数去创建一个8*8的棋盘样式矩阵
z = np.tile(np.array([[0,1],[1,0]]),(4,4))
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [71]:
# 22.对一个5*5的随机矩阵做归一化 (x - min) / (max - min)
z = np.random.random((5,5))
Zmin = z.min()
Zmax = z.max()
z=(z-Zmin)/(Zmax-Zmin)
z 

array([[0.90212703, 0.0185192 , 0.69413218, 0.45900477, 0.8748251 ],
       [0.92659413, 0.39715102, 0.14011648, 0.63058712, 1.        ],
       [0.98688902, 0.42098582, 0.99842676, 0.37991788, 0.47295451],
       [0.51096865, 0.93237364, 0.        , 0.3954201 , 0.05319103],
       [0.25259365, 0.21534902, 0.9786515 , 0.03748386, 0.13226678]])

In [72]:
# 23.创建一个将颜色描述为（RGBA）四个无符号字节的自定义dtype
color = np.dtype([("r",np.dtype,1),
                  ("g",np.dtype,1),
                  ("b",np.dtype,1),
                  ("a",np.dtype,1)])
color 

dtype([('r', 'O'), ('g', 'O'), ('b', 'O'), ('a', 'O')])

In [75]:
# 24.一个5*3的矩阵与一个3*2的矩阵相乘，实矩阵乘积是什么
a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)
np.dot(a,b)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [76]:
# 25.给定一个一维数组，对其在3到8之间的所有元素取反
z = np.arange(11)
z[(3<z)&(z<=8)] *= -1 
z 

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [77]:
# 26.下面脚本运行后的结果是什么
sum(range(5),-1)

9

In [78]:
from numpy import *
sum(range(5),-1)

10

In [79]:
# 26.考虑一个整数向量Z，下列表达式合法的是哪个
z = np.arange(5)
z ** z 

array([  1,   1,   4,  27, 256], dtype=int32)

In [80]:
2 << z >> 2

array([0, 1, 2, 4, 8], dtype=int32)

In [81]:
z <-z

array([False, False, False, False, False])

In [82]:
1j*z 

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [83]:
z /1/1

array([0., 1., 2., 3., 4.])

In [84]:
z < z > z 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [85]:
# 28.下列表达式的结果分别是什么
np.array(0) /np.array(0)

C:\Users\xchwt\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


nan

In [86]:
np.array(0) // np.array(0)

C:\Users\xchwt\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [88]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [89]:
# 29.如何从零位对浮点数组做舍入
z = np.random.uniform(-10,+10,10)
np.copysign(np.ceil(np.abs(z)),z)

array([ 3., -1., 10., -5., 10., 10.,  2., -9., 10.,  4.])

In [91]:
# 30.如何找到两个数组中的共同元素
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)

In [92]:
z1

array([1, 4, 1, 0, 4, 5, 6, 6, 7, 0])

In [93]:
z2

array([2, 2, 7, 1, 3, 7, 4, 7, 2, 4])

In [94]:
np.intersect1d(z1,z2)

array([1, 4, 7])

In [96]:
# 31.如何忽略所用的numpy警告
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

In [97]:
# 32.下面的表达式是正确的吗
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\xchwt\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

In [99]:
# 33.如何得到昨天、今天、明天的日期
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print(str(yesterday),str(today),str(tomorrow))

2019-06-22 2019-06-23 2019-06-24


In [100]:
# 34.如何得到所有与2-16年7月对应的日期
np.arange('2016-07','2016-08',dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [101]:
# 35.如何在位计算(A+B)\*(-A/2)
A = np.ones(3) * 1
B = np.ones(3) * 2
c = np.ones(3) * 3
np.add(A,B,out = B)

array([3., 3., 3.])

In [102]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [103]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [104]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [106]:
# 36.用五种不同的方法提取一个随机数组的整数部分
z = np.random.uniform(0,10,10)
z 

array([7.02576713, 8.01164474, 0.16222064, 4.70572779, 6.29407441,
       7.62014013, 0.35354455, 3.69850888, 0.68698522, 8.29915998])

In [107]:
z - z%1

array([7., 8., 0., 4., 6., 7., 0., 3., 0., 8.])

In [108]:
np.floor(z)

array([7., 8., 0., 4., 6., 7., 0., 3., 0., 8.])

In [109]:
np.ceil(z)-1

array([7., 8., 0., 4., 6., 7., 0., 3., 0., 8.])

In [110]:
z.astype(int)

array([7, 8, 0, 4, 6, 7, 0, 3, 0, 8])

In [111]:
np.trunc(z)

array([7., 8., 0., 4., 6., 7., 0., 3., 0., 8.])

In [112]:
# 37.创建一个5*5的矩阵，其中每行的数值范围从0到4
z = np.zeros((5,5))
z += np.arange(5)
z 

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [113]:
# 38.通过考虑一个可生成10个整数的函数，来构建一个数组
def generate():
    for x in range(10):
        yield x 
z = np.fromiter(generate(),dtype=float,count=-1)
z 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [116]:
# 39.创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [120]:
# 40.创建一个长度为10的随机向量，并将其排序
z = np.random.randn(10)
z.sort()
z 

array([-1.18856365, -0.89475994, -0.5387246 , -0.40052662,  0.45994298,
        0.60339756,  0.91228464,  1.03886139,  1.18138266,  2.1823221 ])

numpy.random.randn(d0,d1,…,dn)是从标准正态分布中返回一个或多个样本值。

numpy.random.rand(d0,d1,…,dn) 的随机样本位于[0,1) 中

random() 方法返回随机生成的一个实数，random()是不能直接访问的，需要导入 random 模块，然后通过 random 静态对象调用该方法。random.random()

In [121]:
# 41.对于一个小数组，如何用比np.sum更快的方法对其求和
z = np.arange(10)
np.add.reduce(z)

45

In [123]:
# 42.对于两个随机数组A和B，检查它们是否相等
A = np.random.randint(0,3,5)
B = np.random.randint(0,3,5)
print(A,B)

[0 2 2 2 0] [2 2 0 0 0]


In [124]:
equal = np.allclose(A,B)
equal

False

In [126]:
# 43.创建一个只读数组
z = zeros(10)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

In [127]:
# 44.将笛卡尔坐标下的一个10*2的矩阵转换为极坐标形式
Z = np.random.random((10,2))
X,Y = Z[:,0],Z[:,1]
R = np.sqrt(X**2,Y**2)
T = np.arctan2(Y,X)
print(R,T)

[0.16798713 0.49315462 0.57470433 0.67408127 0.29458863 0.63004651
 0.33220069 0.79798942 0.14180325 0.32929229] [1.26612334 0.85273384 0.8973354  0.88660359 1.28020044 0.03679269
 1.16938796 0.81696739 1.41004901 1.24473012]


In [128]:
# 45.创建一个长度为10的向量，并将向量中最大值替换为1
z = np.random.random(10)
z[z.argmax()] = 0
z 

array([0.        , 0.47206787, 0.46570599, 0.61553146, 0.6924931 ,
       0.25813505, 0.52557962, 0.22207182, 0.86595881, 0.0925536 ])

In [130]:
# 46.创建一个结构化数组，并实现x和y坐标覆盖[0,1]x[0,1] 区域
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
Z 

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

In [ ]:
# 47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))


In [131]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [132]:
#48. 打印每个numpy标量类型的最小值和最大值？
for dtype in [np.int8, np.int32, np.int64]:
     print(np.iinfo(dtype).min)
     print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
     print(np.finfo(dtype).min)
     print(np.finfo(dtype).max)
     print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [135]:
# 48.如何打印一个数组中的所有数值
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
Z 

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [136]:
# 50. 给定标量时，如何找到数组中最接近标量的值？
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
rint (Z[index])

18.0

In [137]:
# 51. 创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [138]:
# 52. 对一个表示坐标形状为(100,2)的随机向量，找到点与点的距离
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[0.         0.4066908  0.68130327 0.2517214  0.04709732 0.65562228
  0.2813011  0.60844411 0.5494303  0.37666059]
 [0.4066908  0.         0.59031411 0.30655056 0.42832351 0.62650915
  0.44365341 0.27956642 0.65407675 0.17286766]
 [0.68130327 0.59031411 0.         0.43645599 0.65536593 0.09826419
  0.42391049 0.41592688 0.29975021 0.42725635]
 [0.2517214  0.30655056 0.43645599 0.         0.23619623 0.42520412
  0.13710613 0.39897782 0.37651179 0.17779291]
 [0.04709732 0.42832351 0.65536593 0.23619623 0.         0.62431176
  0.24502914 0.61190036 0.50896676 0.3790312 ]
 [0.65562228 0.62650915 0.09826419 0.42520412 0.62431176 0.
  0.38219408 0.48795822 0.20925337 0.45582689]
 [0.2813011  0.44365341 0.42391049 0.13710613 0.24502914 0.38219408
  0.         0.5055807  0.27235309 0.30498383]
 [0.60844411 0.27956642 0.41592688 0.39897782 0.61190036 0.48795822
  0.5055807  0.         0.60280036 0.23286937]
 [0.5494303  0.65407675 0.29975021 0.37651179 0.50896676 0.20925337
  0.27235309 0.60280

In [139]:
# 53. 如何将32位的浮点数(float)转换为对应的整数(integer)?
Z = arange(10,dtype=np.float32)
Z = Z.astype(np.int32,copy=False)
Z 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 54.如何读取以下文件
'''1, 2, 3, 4, 5
   6,  ,  , 7, 8
    ,  , 9,10,11   '''


In [140]:
# 55. 对于numpy数组，enumerate的等价操作是什么？
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
     print (index, value)
for index in np.ndindex(Z.shape):
     print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [141]:
#56. 生成一个通用的二维Gaussian-like数组 
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [142]:
# 57. 对一个二维数组，如何在其内部随机放置p个元素?
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]]


In [143]:
# 58. 减去一个矩阵中的每一行的平均值
X = np.random.rand(5,10)
Y = X - X.mean(axis=1,keepdims=True)
Y

array([[-0.11509171,  0.12979971,  0.22042955,  0.21338863, -0.00455377,
        -0.05980746,  0.12721476,  0.05593687, -0.2062691 , -0.36104747],
       [ 0.35579963,  0.23306407,  0.40177375, -0.36292445, -0.26737496,
        -0.4768744 ,  0.15002975, -0.25070737,  0.25658016, -0.03936618],
       [ 0.34443571, -0.16017529, -0.40268673, -0.31089182,  0.35815656,
         0.31452361, -0.19074134,  0.02332403,  0.32759229, -0.30353702],
       [-0.01945022,  0.27040371,  0.4345953 , -0.24413222, -0.05721348,
        -0.4387622 ,  0.41344915,  0.01920973,  0.01121435, -0.38931411],
       [-0.46626636, -0.26544886,  0.04984965,  0.350359  ,  0.2649685 ,
         0.00059469,  0.00756865, -0.0691824 ,  0.19724732, -0.06969019]])

In [144]:
# 59. 如何通过第n列对一个数组进行排序?
z = np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[5 3 9]
 [8 7 3]
 [3 3 2]]
[[5 3 9]
 [3 3 2]
 [8 7 3]]


In [145]:
print(z[z[1,:].argsort()])

[[3 3 2]
 [8 7 3]
 [5 3 9]]


In [147]:
# 61. 从数组中的给定值中找出最近的值 
Z = np.random.uniform(0,1,10)
print(Z)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

[0.63141546 0.49094178 0.65522364 0.14972596 0.77145132 0.77902915
 0.53118703 0.15002965 0.41564213 0.52531301]
0.4909417802692314


In [148]:
# 62. 如何用迭代器(iterator)计算两个分别具有形状(1,3)和(3,1)的数组?
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [149]:
# 63. 创建一个具有name属性的数组类
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [150]:
# 64. 考虑一个给定的向量，如何对由第二个向量索引的每个元素加1(小心重复的索引)? 
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 5. 1. 3. 1. 2. 2. 7. 3. 4.]


In [151]:
#65. 根据索引列表(I)，如何将向量(X)的元素累加到数组(F)? 
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [152]:
#66. 考虑一个(dtype=ubyte) 的 (w,h,3)图像，计算其唯一颜色的数量
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8
